version: '3'
services:
  mysql-docker-container:
    image: mysql:8.0.15
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    hostname: mysql-docker-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: questionnairedb_test
      MYSQL_USER: sboot
      MYSQL_PASSWORD: sboot
#    container_name: mysql-docker-container
#    networks:
#      - my_mysql_net

  app:
    image: simplepolling
    restart: always
    depends_on:
      - mysql-docker-container
    ports:
      - "8080:8080"
#    links:
#      - mysql-docker-container
#    networks:
#      - my_mysql_net
#
#networks:
#  my_mysql_net:
#    driver: bridge
