spring:
  # active profile setting
  profiles:
    active: postgres-docker

  # Spring Data JPA settings
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  # Thymeleaf settings
  thymeleaf:
    cache: false
    prefix: classpath:/templates

# Tomcat server settings
server:
  port: 8080

---
# 開発環境の設定
spring:
  profiles: development

  # h2 database settings
  h2:
    console:
      enabled: true
      path: /h2-console

---
# 本番環境の設定
spring:
  profiles: postgres

  # Postgres database settings
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/questionnairedb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true

---
# 本番環境の設定
spring:
  profiles: postgres-docker

  # Postgres database settings
  datasource:
    url: jdbc:postgresql://postgres-dev:5432/questionnairedb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true

---
# 本番環境の設定
spring:
  profiles: mariadb

  # mariadb database settings
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/questionnairedb_test
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

---
# 本番環境の設定
spring:
  profiles: mysql

  # mysql database settings
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/questionnairedb_test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Spring Data JPA settings
  jpa:
    hibernate:
      ddl-auto: update

---
# 本番環境の設定
spring:
  profiles: mysql-docker

  # mysql database settings
  datasource:
    url: jdbc:mysql://mysql-docker-container:3307/questionnairedb_test
    username: sboot
    password: sboot
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Spring Data JPA settings
  jpa:
    hibernate:
      ddl-auto: update
