spring:
  # active profile setting
  profiles:
    active: development

  # Spring Data JPA settings
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  # Thymeleaf settings
  thymeleaf:
    cache: false
    prefix: classpath:/templates

# Tomcat server settings
server:
  port: 8080

---
# 開発環境の設定
spring:
  profiles: development

  # h2 database settings
  h2:
    console:
      enabled: true
      path: /h2-console

